# Personal AI Board - LLM Providers Configuration Example
# This file shows how to configure different LLM providers

# Database configuration
database:
  path: "personal_ai_board.db"
  max_open_conns: 25
  max_idle_conns: 25
  enable_wal: true
  enable_foreign_keys: true

# Logging configuration
log:
  level: "info"
  format: "text"

# LLM configuration
llm:
  # Default provider to use if none specified
  default_provider: "openai"

  # Default model settings
  default_model: "gpt-4"
  temperature: 0.7
  max_tokens: 1000
  timeout: "30s"

  # OpenAI configuration
  openai:
    api_key: "${OPENAI_API_KEY}"  # Set via environment variable
    base_url: "https://api.openai.com/v1"
    models:
      - "gpt-4"
      - "gpt-4-turbo"
      - "gpt-4o"
      - "gpt-3.5-turbo"

  # Anthropic Claude configuration
  anthropic:
    api_key: "${ANTHROPIC_API_KEY}"  # Set via environment variable
    base_url: "https://api.anthropic.com"
    models:
      - "claude-3-opus-20240229"
      - "claude-3-sonnet-20240229"
      - "claude-3-haiku-20240307"
      - "claude-2.1"
      - "claude-instant-1.2"

  # Google Gemini configuration
  google:
    api_key: "${GOOGLE_API_KEY}"  # Set via environment variable
    base_url: "https://generativelanguage.googleapis.com"
    models:
      - "gemini-1.5-pro"
      - "gemini-1.5-flash"
      - "gemini-1.0-pro"
      - "gemini-1.0-pro-vision"

# Analysis configuration
analysis:
  max_concurrent: 5
  default_mode: "discussion"

  # Provider preferences for different analysis modes
  mode_providers:
    discussion: ["openai", "anthropic"]  # Best for conversational analysis
    simulation: ["openai", "google"]     # Good for scenario modeling
    analysis: ["anthropic", "google"]    # Strong analytical capabilities
    comparison: ["openai", "anthropic"]  # Good for side-by-side analysis
    evaluation: ["anthropic", "google"]  # Strong reasoning capabilities
    prediction: ["openai", "google"]     # Good for forecasting

# Memory configuration
memory:
  retention_days: 90
  short_term_limit: 50
  long_term_limit: 200

# Provider-specific settings
providers:
  openai:
    # OpenAI specific settings
    retry_attempts: 3
    retry_delay: "1s"

  anthropic:
    # Anthropic specific settings
    retry_attempts: 3
    retry_delay: "2s"

  google:
    # Google specific settings
    retry_attempts: 3
    retry_delay: "1s"
    safety_settings:
      harassment: "BLOCK_MEDIUM_AND_ABOVE"
      hate_speech: "BLOCK_MEDIUM_AND_ABOVE"
      sexually_explicit: "BLOCK_MEDIUM_AND_ABOVE"
      dangerous_content: "BLOCK_MEDIUM_AND_ABOVE"

# Example persona configurations for different providers
example_personas:
  # Creative persona optimized for OpenAI
  creative_visionary:
    provider: "openai"
    model: "gpt-4"
    temperature: 0.9
    traits:
      creativity: 10
      risk_tolerance: 8
      optimism: 9

  # Analytical persona optimized for Anthropic
  analytical_strategist:
    provider: "anthropic"
    model: "claude-3-opus-20240229"
    temperature: 0.3
    traits:
      analytical: 10
      systematic: 9
      risk_tolerance: 4

  # Balanced persona optimized for Google
  balanced_advisor:
    provider: "google"
    model: "gemini-1.5-pro"
    temperature: 0.6
    traits:
      analytical: 7
      creativity: 7
      empathy: 8
      optimism: 6

# Cost management
cost_management:
  # Daily budget limits per provider (in USD)
  daily_budgets:
    openai: 10.00
    anthropic: 15.00
    google: 8.00

  # Token usage alerts
  token_alerts:
    daily_limit: 100000
    warning_threshold: 80000

  # Model cost preferences (prefer cheaper models when possible)
  cost_optimization:
    enabled: true
    fallback_models:
      openai: ["gpt-3.5-turbo", "gpt-4"]
      anthropic: ["claude-3-haiku-20240307", "claude-3-sonnet-20240229"]
      google: ["gemini-1.5-flash", "gemini-1.5-pro"]
